name: Publish on NuGet

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Build and publish packages
    runs-on: ubuntu-latest
    environment:
      name: nuget
      url: https://github.com
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Build and publish Hanji.Sdk if version changed
        uses: alirezanet/publish-nuget@v3.0.3
        with:
          PROJECT_FILE_PATH: Hanji.Sdk/Hanji.Sdk.csproj
          PACKAGE_NAME: Hanji.Sdk
          NUGET_KEY: ${{ secrets.NUGET_KEY }}